// GENERATED — do not edit by hand.
// Source: AverageMarketCapitalization30Jun2026.xlsx (100 large, 150 mid,
// 5177 small companies, SEBI categorisation).
// Regenerate:  python scripts/gen_market_cap.py
// Verify:      python scripts/gen_market_cap.py --check
//
// Only ranks 1-250 are listed: SEBI defines 251+ as Small, so every
// symbol absent from both sets is Small by definition.


export const LARGE: ReadonlySet<string> = new Set([
  "ABB", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS",
  "ADANIPOWER", "AMBUJACEM", "APOLLOHOSP", "ASIANPAINT", "AXISBANK",
  "BAJAJ-AUTO", "BAJAJFINSV", "BAJAJHLDNG", "BAJFINANCE", "BANKBARODA",
  "BEL", "BHARTIARTL", "BHEL", "BPCL", "BRITANNIA", "BSE", "CANBK",
  "CGPOWER", "CHOLAFIN", "CIPLA", "COALINDIA", "CUMMINSIND", "DIVISLAB",
  "DLF", "DMART", "EICHERMOT", "ETERNAL", "GAIL", "GODREJCP", "GRASIM",
  "GROWW", "HAL", "HCLTECH", "HDFCAMC", "HDFCBANK", "HDFCLIFE",
  "HINDALCO", "HINDUNILVR", "HINDZINC", "HYUNDAI", "ICICIAMC",
  "ICICIBANK", "IDEA", "INDIANB", "INDIGO", "INDUSTOWER", "INFY", "IOC",
  "IRFC", "ITC", "JINDALSTEL", "JIOFIN", "JSWSTEEL", "KOTAKBANK", "LICI",
  "LT", "LTM", "M&M", "MARUTI", "MOTHERSON", "MUTHOOTFIN", "NESTLEIND",
  "NTPC", "ONGC", "PFC", "PIDILITIND", "PNB", "POLYCAB", "POWERGRID",
  "POWERINDIA", "RELIANCE", "SBILIFE", "SBIN", "SHRIRAMFIN", "SIEMENS",
  "SOLARINDS", "SUNPHARMA", "TATACAP", "TATACONSUM", "TATAPOWER",
  "TATASTEEL", "TCS", "TECHM", "TITAN", "TMCV", "TMPV", "TORNTPHARM",
  "TRENT", "TVSMOTOR", "ULTRACEMCO", "UNIONBANK", "VAML", "VBL", "VEDL",
  "WIPRO",
]);

export const MID: ReadonlySet<string> = new Set([
  "360ONE", "3MINDIA", "ABBOTINDIA", "ABCAPITAL", "AIAENG", "AIIL",
  "AJANTPHARM", "ALKEM", "ANTHEM", "APARINDS", "APLAPOLLO", "ASHOKLEY",
  "ASTERDM", "ASTRAL", "ATGL", "AUBANK", "AUROPHARMA", "BAGMANE",
  "BAJAJHFL", "BALKRISIND", "BANKINDIA", "BDL", "BERGEPAINT",
  "BHARATFORG", "BHARTIHEXA", "BIOCON", "BLUESTARCO", "BOSCHLTD",
  "COCHINSHIP", "COFORGE", "COLPAL", "CONCOR", "COROMANDEL", "DABUR",
  "DALBHARAT", "DIXON", "DRREDDY", "EMBASSY", "ENDURANCE", "ENRIN",
  "ESCORTS", "FACT", "FEDERALBNK", "FLUOROCHEM", "FORTIS", "GICRE",
  "GLAXO", "GLENMARK", "GMRAIRPORT", "GODFRYPHLP", "GODREJIND",
  "GODREJPROP", "GVT&D", "HAVELLS", "HDBFS", "HEROMOTOCO", "HINDCOPPER",
  "HINDPETRO", "HUDCO", "ICICIGI", "ICICIPRULI", "IDBI", "IDFCFIRSTB",
  "INDHOTEL", "INDUSINDBK", "IOB", "IPCALAB", "IRCTC", "IREDA",
  "ITCHOTELS", "JKCEMENT", "JSL", "JSWENERGY", "JSWINFRA", "KALYANKJIL",
  "KEI", "KRT", "LAURUSLABS", "LENSKART", "LGEINDIA", "LINDEINDIA",
  "LLOYDSME", "LODHA", "LTF", "LTTS", "LUPIN", "M&MFIN", "MAHABANK",
  "MANKIND", "MARICO", "MAXHEALTH", "MAZDOCK", "MCX", "MEESHO", "MFSL",
  "MOTILALOFS", "MPHASIS", "MRF", "NAM-INDIA", "NATIONALUM", "NAUKRI",
  "NH", "NHPC", "NLCINDIA", "NMDC", "NTPCGREEN", "NYKAA", "OBEROIRLTY",
  "OFSS", "OIL", "PAGEIND", "PATANJALI", "PAYTM", "PERSISTENT",
  "PETRONET", "PGHH", "PHOENIXLTD", "PIIND", "PIRAMALFIN", "POLICYBZR",
  "POONAWALLA", "PREMIERENE", "PRESTIGE", "RADICO", "RECLTD", "RVNL",
  "SAIL", "SBICARD", "SCHAEFFLER", "SHREECEM", "SONACOMS", "SRF",
  "SUNDARMFIN", "SUPREMEIND", "SUZLON", "SWIGGY", "TATACOMM", "THERMAX",
  "TIINDIA", "TORNTPOWER", "UBL", "UCOBANK", "UNITDSPR", "UNOMINDA",
  "UPL", "VMM", "VOLTAS", "WAAREEENER", "YESBANK", "ZYDUSLIFE",
]);
